services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend.dev
    container_name: backend-app
    ports:
      - "3001:3001"
    environment:
      DB_HOST: my-database
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: postgres
      DB_PORT: 5432
    depends_on:
      - my-database
    networks:
      - my-network

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my-network

  my-database:
    image: postgres
    container_name: my-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:

volumes:
  db_data: