version: "3.9"

services:
  backend:
    image: ${DOCKER_USERNAME}/backend-app:${BACKEND_TAG}
    container_name: backend-app
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: ${DATABASE_URL}

  frontend:
    image: ${DOCKER_USERNAME}/frontend-app:${FRONTEND_TAG}
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
