services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend.prod
    container_name: backend-app
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: ${DATABASE_URL}

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  