FROM node:22-alpine
RUN npm install -g pnpm
WORKDIR /app
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./packages ./packages
COPY ./apps/backend ./apps/backend

RUN  pnpm install --filter backend...
# Generate Prisma client
RUN pnpm --filter @repo/db exec prisma generate

# Build backend
RUN pnpm --filter backend run build

EXPOSE 3001
CMD ["sh","-c","pnpm --filter @repo/db exec prisma migrate deploy && pnpm --filter backend run start"]
