FROM node:22-alpine
RUN npm install -g pnpm
WORKDIR /app
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./packages ./packages
COPY ./apps/frontend ./apps/frontend
RUN  pnpm install --filter frontend...
# Build frontend
RUN pnpm --filter frontend run build
EXPOSE 3000
CMD ["pnpm","--filter","frontend","run","start"]